### ISSUE TITLE
RespeQt settings

### ISSUE THREAD

**Issue by atari8warez** [jzatarski/RespeQt#24]
The first time it is used, RespeQt tries to import settings from AspeQt if the latter was used before RespeQt is installed. It does however import ALL settings, whether they are relevant to RespeQt or not, causing bloat and confusion in the registry entries.

**Comment by jzatarski** [comment]
given RespeQt is a fork of AspeQt, there are likely no setting AspeQt would keep that RespeQt wouldn't. If you would show me examples, that would make this much more clear.

**Comment by atari8warez** [comment]
AspeQt is still being developed (although does not reside in the old repository) and the latest release had already nearly 90 downloads (Windows version - Ubuntu will follow shortly), so assuming that AspeQt would have no settings different than RespeQt is ignoring the fact that not everybody uses RespeQt. The solution is simple, just migrate the settings that has relevance to RespeQt.

**Comment by jzatarski** [comment]
There has been a report by another user that RespeQt was having issues due to some settings it imported from AspeQt which it was using. Evidently, these values form AspeQt were not compatible with RespeQt. This has made me realize, that even if RespeQt only imports setting from AspeQt which it uses, that these settings may not even have compatible values as AspeQt and RespeQt drift apart further. In addition, the number of settings which need to be configured in RespeQt is only a small number, and the configuration only needs to be done once. For that reason, I am dropping support to migrate settings from AspeQt entirely in order to prevent future issues.
