### ISSUE TITLE
OS X build crashes on exit

### ISSUE THREAD

**Issue by josch1710** [jzatarski/RespeQt#39]
When I close RespeQt on OSX, I get a crash dialog from the os.
I run it on OS X 10.11 (El Capitan).

**Comment by josch1710** [comment]
Well, it crashed. But now it don't.
Scratching my heading, I close this for now.

**Comment by jzatarski** [comment]
sometimes crashes can be caused by certain conditions, maybe you had the options dialog or a logging dialog open when you closed it? this has caused issues on windows in the past, though I fixed it by ensuring any dialogs were closed before the main application exited.

Found the commit, 5983aa8 , seems it was diskeditdialogs that needed to be closed before exit.

**Comment by blind** [comment]
I fixed a crash like this on the blind-fixes branch. It seems the MainWindow::closeEvent is called twice when the application is quitting. That caused a double release of some windows.
See https://github.com/blind/RespeQt/commit/69548b1551e1423ecd81e512c37e9534616e3c5a

**Comment by blind** [comment]
My "fix" only removes the crash though, the method is still called twice, I don't know why.
